// src/components/navbar/index.tsx
import "./nav.css"
function NavLinks() {
return <>
<li><a>About</a></li>
        <li><a>Projects</a></li>
<li><a>Contact</a></li>
</>
}
export default function Navbar() {
    return <div className="navbar" style={{ zIndex: 9999, background: "var(--base)", position: "fixed",  }}>
    <div className="navbar-start">
      <div className="dropdown">
        <div tabIndex={0} role="button" className="btn btn-ghost lg:hidden">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
        </div>
        <ul tabIndex={0} className="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52 nav-links">
       <NavLinks />
      </ul>
      </div>
      <a className="btn btn-ghost text-xl">saahild.com</a>
    
      <div className="navbar-center hidden lg:flex">
      <ul className="menu menu-horizontal px-1 nav-links">
        <NavLinks />
      </ul>
    </div>
    </div>
    <div className="navbar-end">
      {/* <a className="btn">Button</a> */}
    </div>
  </div>
}

// components/Navbar.vue
<template>
  <div class="navbar bg-base-100 shadow-sm">
    <div class="navbar-start">
      <div class="dropdown">
        <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-5 w-5"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M4 6h16M4 12h8m-8 6h16"
            />
          </svg>
        </div>
        <ul
          tabindex="0"
          class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow"
        >
          <li><a>Item 1</a></li>
          <li><a>Item 3</a></li>
        </ul>
      </div>
      <a class="btn btn-ghost text-xl">saahild.com</a>
    </div>
    <!-- <div class="navbar-center hidden lg:flex">
     
    </div> -->
    <div class="navbar-end">
      <ul class="menu menu-horizontal px-1 hidden lg:flex">
        <li><a>Item 1</a></li>
        <li><a>Item 3</a></li>
      </ul>
    </div>
  </div>
</template>
